services:
  - type: worker
    name: power-ladder-auto-save
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python auto_save.py
    schedule: "*/5 * * * *"  # 5분 간격
    envVars:
      - key: GOOGLE_SHEET_JSON
        value: <여기에 환경변수 값이 설정되어 있어야 함>
