name: Auto Save Recent Result

on:
  schedule:
    - cron: '*/5 * * * *'  # 매 5분마다 실행 (UTC 기준, 한국은 +9시간)
  workflow_dispatch:  # 수동 실행 버튼도 추가

jobs:
  auto-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client requests

      - name: Run auto_save script
        env:
          GOOGLE_SHEET_JSON: ${{ secrets.GOOGLE_SHEET_JSON }}
        run: |
          python auto_save.py
